### ISSUE TITLE
Add lgpl-3 license

### ISSUE THREAD

**Issue by 1nikolas** [marcoscgdev/Licenser#10]
Could you add lgpl-3.0?
https://www.gnu.org/licenses/lgpl-3.0.en.html

**Comment by marcoscgdev** [comment]
Added as _License.LGPL3_ in [version 1.0.7](https://github.com/marcoscgdev/Licenser/releases/tag/1.0.7).

**Comment by 1nikolas** [comment]
Thank you! Really like your library
