### ISSUE TITLE
Add SIL Open Font License

### ISSUE THREAD

**Issue by alexeyvasilyev** [marcoscgdev/Licenser#11]
https://en.wikipedia.org/wiki/SIL_Open_Font_License

Material Design Icons comes under this license
https://github.com/templarian/MaterialDesign

**Comment by marcoscgdev** [comment]
SIL Open Font License v1.1 added in [version 2.0.0](https://github.com/marcoscgdev/Licenser/releases/tag/2.0.0) as OFL1_1.
