### ISSUE TITLE
add MPL2 license

### ISSUE THREAD

**Issue by jisungbin** [marcoscgdev/Licenser#12]
Can you add [MPL2](https://github.com/mozilla/rhino/blob/master/LICENSE.txt)?

MPL2 is Mozilla Public License 2.0.

**Comment by marcoscgdev** [comment]
Mozilla Public License 2.0 added in [version 2.0.0](https://github.com/marcoscgdev/Licenser/releases/tag/2.0.0) as MPL2. Versions 1.0 and 1.1 have also been added.
