### ISSUE TITLE
How could I change the webview's background color?

### ISSUE THREAD

**Issue by xo-pixels** [marcoscgdev/Licenser#4]
![screenshot_1534356985](https://user-images.githubusercontent.com/27860259/44165124-9350fc00-a0d0-11e8-80a7-ea052a0a0ed6.png)

**Comment by marcoscgdev** [comment]
At this moment, webview's background color is based on your app theme (light or dark based). I will probably add an option to change the webview's background color in a few days.

**Comment by marcoscgdev** [comment]
Feature added in [Version 1.0.3](https://github.com/marcoscgdev/Licenser/releases/tag/1.0.3).

**Comment by xo-pixels** [comment]
Thank You 🙏
