### ISSUE TITLE
ISC License

### ISSUE THREAD

**Issue by F4bioo** [marcoscgdev/Licenser#7]
Hello can you add ISC License
https://opensource.org/licenses/ISC

**Comment by F4bioo** [comment]
Hi, I can see ISC license here: [public static int ISC = 5;](https://github.com/marcoscgdev/Licenser/blob/caef111cfaf5fb87f1f68a6de8e245d6f8183002/licenser/src/main/java/com/marcoscg/licenser/License.java#L13)
But not here: [Version 1.0.4.](https://github.com/marcoscgdev/Licenser/releases/tag/1.0.4)

**Comment by marcoscgdev** [comment]
I know. That is because I have not made the new release yet.

**Comment by marcoscgdev** [comment]
Added in [Version 1.0.5](https://github.com/marcoscgdev/Licenser/releases/tag/1.0.5).
