### ISSUE TITLE
Generated dialog is blank on Android 10

### ISSUE THREAD

**Issue by RoboticSquirrel94** [marcoscgdev/Licenser#8]
This could be an issue with loading content into a web view:

Possible fix - perform Base64 encoding on HTML string before loading it into a WebView.

Example:
```
String html_code= "<html><body>Your Actualtext.</body></html>";
String encodedHtml = Base64.encodeToString(html_code.getBytes(), Base64.NO_PADDING);
webview.getSettings().setJavaScriptEnabled(true);
webview.loadData(encodedHtml , "text/html", "base64");
```

Source : https://stackoverflow.com/questions/58182412/webviews-loaddata-is-not-working-in-android-10-0-q

**Comment by marcoscgdev** [comment]
Fixed in [version 1.0.6](https://github.com/marcoscgdev/Licenser/releases/tag/1.0.6). Thanks for your report and thanks to @petrikq for making the pull request.
